//+build !noasm !appengine
// AUTO-GENERATED BY C2GOASM -- DO NOT EDIT

TEXT ·__add_float32(SB), $296-24

	MOVQ buf1+0(FP), DI
	MOVQ buf2+8(FP), SI
	MOVQ res+16(FP), DX
	ADDQ $8, SP

	LONG $0x247c8948; BYTE $0x70         // mov    qword [rsp + 112], rdi
	LONG $0x24748948; BYTE $0x68         // mov    qword [rsp + 104], rsi
	LONG $0x24548948; BYTE $0x60         // mov    qword [rsp + 96], rdx
	LONG $0x24548b48; BYTE $0x70         // mov    rdx, qword [rsp + 112]
	LONG $0x24548948; BYTE $0x78         // mov    qword [rsp + 120], rdx
	LONG $0x24548b48; BYTE $0x78         // mov    rdx, qword [rsp + 120]
	LONG $0x0210fcc5                     // vmovups    ymm0, yword [rdx]
	LONG $0x4429fcc5; WORD $0x4024       // vmovaps    yword [rsp + 64], ymm0
	LONG $0x24548b48; BYTE $0x68         // mov    rdx, qword [rsp + 104]
	QUAD $0x0000010824948948             // mov    qword [rsp + 264], rdx
	QUAD $0x0000010824948b48             // mov    rdx, qword [rsp + 264]
	LONG $0x0210fcc5                     // vmovups    ymm0, yword [rdx]
	LONG $0x4429fcc5; WORD $0x2024       // vmovaps    yword [rsp + 32], ymm0
	LONG $0x4428fcc5; WORD $0x4024       // vmovaps    ymm0, yword [rsp + 64]
	LONG $0x4c28fcc5; WORD $0x2024       // vmovaps    ymm1, yword [rsp + 32]
	QUAD $0x0000e0248429fcc5; BYTE $0x00 // vmovaps    yword [rsp + 224], ymm0
	QUAD $0x0000c0248c29fcc5; BYTE $0x00 // vmovaps    yword [rsp + 192], ymm1
	QUAD $0x0000e0248428fcc5; BYTE $0x00 // vmovaps    ymm0, yword [rsp + 224]
	QUAD $0x0000c0248458fcc5; BYTE $0x00 // vaddps    ymm0, ymm0, yword [rsp + 192]
	LONG $0x0429fcc5; BYTE $0x24         // vmovaps    yword [rsp], ymm0
	LONG $0x24548b48; BYTE $0x60         // mov    rdx, qword [rsp + 96]
	LONG $0x0428fcc5; BYTE $0x24         // vmovaps    ymm0, yword [rsp]
	QUAD $0x000000b824948948             // mov    qword [rsp + 184], rdx
	QUAD $0x000080248429fcc5; BYTE $0x00 // vmovaps    yword [rsp + 128], ymm0
	QUAD $0x000080248428fcc5; BYTE $0x00 // vmovaps    ymm0, yword [rsp + 128]
	QUAD $0x000000b824948b48             // mov    rdx, qword [rsp + 184]
	LONG $0x0211fcc5                     // vmovups    yword [rdx], ymm0
	SUBQ $8, SP
	VZEROUPPER
	RET
